mycloud/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.views import serve

from pan.urls import router

urlpatterns = [
    path('', include('pan.urls')),
    path('api/', include(router.urls)),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('favicon.ico', serve, {'path': 'favicon.ico'}),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + [
        path('__debug__/', include('debug_toolbar.urls'))
    ]
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler400 = 'pan.views.bad_request_view'
handler403 = 'pan.views.permission_denied_view'
handler404 = 'pan.views.not_found_view'
handler500 = 'pan.views.server_error_view'

pan/urls.py
from django.urls import path
from rest_framework.routers import SimpleRouter

from pan import views

app_name = 'pan'

# 主要页面
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('home', views.HomeView.as_view(), name="home"),
    path('detail', views.FileDetailView.as_view(), name='detail'),
    path('share', views.FileShareView.as_view(), name='share')
]

# 上传
urlpatterns += [
    path('file/upload', views.FileUploadView.as_view(), name='file-upload'),
    path('folder/upload', views.FolderUploadView.as_view(), name='folder-upload'),
]

# 验证
urlpatterns += [
    path('login', views.LoginView.as_view(), name='login'),
    path('register', views.RegisterView.as_view(), name='register'),
    path('logout', views.LogoutView.as_view(), name='logout'),
    path('password', views.PasswordView.as_view(), name='password'),
    path('reset', views.ResetView.as_view(), name='reset'),
    path('reset-done/<str:param>', views.ResetDoneView.as_view(), name='reset-done'),
]

# restful api
router = SimpleRouter(trailing_slash=False)
router.register('file', views.FileViewSet, 'file')
router.register('share', views.FileShareViewSet, 'share')
router.register('recycle', views.RecycleViewSet, 'recycle')
router.register('letter', views.LetterViewSet, 'letter')
router.register('notice', views.NoticeViewSet, 'notice')
router.register('profile', views.ProfileViewSet, 'profile')

pan/views.py
from pathlib import Path
from datetime import timedelta
from collections import defaultdict

from django.conf import settings
from django.contrib.auth import login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.signing import Signer, TimestampSigner, BadSignature, SignatureExpired
from django.core.mail import send_mail
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView
from django.views.decorators.csrf import ensure_csrf_cookie
from django.db import transaction
from django.http import FileResponse
from django.shortcuts import render
from django.template.loader import render_to_string
from rest_framework import status, mixins, permissions
from rest_framework.response import Response
from rest_framework.decorators import action
from rest_framework.views import APIView
from rest_framework.viewsets import GenericViewSet

from pan.models import (
    GenericFile, RecycleFile, FileType,
    FileShare, AcceptRecord, Notice, Profile
)
from pan.serializers import (
    LoginSerializer, RegisterSerializer, PasswordSerializer, ProfileSerializer, UserSerializer,
    NoticeSerializer, LetterSerializer, FileSerializer, RecycleSerializer, FileShareSerializer
)
from pan.utils import AjaxData, get_key_signature, make_archive_bytes, get_uuid


@method_decorator(ensure_csrf_cookie, 'get')
class IndexView(TemplateView):
    """首页"""
    template_name = 'pan/index.html'


@method_decorator(ensure_csrf_cookie, 'get')
class HomeView(LoginRequiredMixin, TemplateView):
    """主页面"""
    template_name = 'pan/home.html'


class FileDetailView(LoginRequiredMixin, TemplateView):
    """文件详情"""
    template_name = 'pan/detail.html'


class FileShareView(TemplateView):
    """链接获取文件"""
    template_name = 'pan/share.html'


class ResetDoneView(TemplateView):
    """重置密码结果"""
    template_name = 'pan/reset_done.html'

    def get_context_data(self, **kwargs):
        param = kwargs.get('param')
        context = super().get_context_data()
        try:
            auth = TimestampSigner().unsign_object(param, max_age=settings.TOKEN_EXPIRY)
            if not auth.get('token') or not auth.get('user') or auth['token'] != settings.RESET_TOKEN:
                context['access'] = False
            else:
                user = User.objects.get(username=auth['user'])
                user.set_password(settings.RESET_PASSWORD)
                user.save()
                context['access'] = True
        except (BadSignature, SignatureExpired):
            context['access'] = False
        return context


class LoginView(APIView):
    """登录"""
    permission_classes = [permissions.AllowAny]

    def post(self, request):
        serializer = LoginSerializer(data=request.data, context={'request': request})
        if serializer.is_valid():
            login(request, serializer.validated_data['user'])
            expiry = request.session.get_expiry_date().timestamp()
            if not serializer.validated_data['remember']:
                request.session.set_expiry(0)
                expiry = timezone.now().timestamp()
            data = {
                'terms': request.session['terms'],
                'expiry': expiry,
                'profile': serializer.validated_data['profile'],
            }
            result = AjaxData(msg='登录成功', data=data)
            return Response(result)
        else:
            result = AjaxData(400, errors=serializer.errors)
            return Response(result)


class RegisterView(APIView):
    """注册"""
    permission_classes = [permissions.AllowAny]

    def post(self, request):
        serializer = RegisterSerializer(data=request.data)
        if serializer.is_valid():
            username = serializer.validated_data['username']
            password = serializer.validated_data['password1']
            User.objects.create_user(username=username, password=password)
            result = AjaxData(msg='注册成功')
            return Response(result)
        else:
            result = AjaxData(400, errors=serializer.errors)
            return Response(result)


class LogoutView(APIView):
    """登出"""

    def get(self, request):
        logout(request)
        return Response()


class PasswordView(APIView):
    """修改密码"""

    def post(self, request):
        serializer = PasswordSerializer(data=request.data, context={'request': request})
        if serializer.is_valid():
            request.user.set_password(serializer.validated_data['password1'])
            request.user.save()
            result = AjaxData(msg='修改成功')
            return Response(result)
        else:
            result = AjaxData(400, errors=serializer.errors)
            return Response(result)


class ResetView(APIView):
    """重置密码"""

    permission_classes = [permissions.AllowAny]

    def post(self, request):
        username = request.data.get('username').strip()
        queryset = User.objects.filter(username=username)

        if not queryset.exists() or not queryset.get().email:
            result = AjaxData(400, errors={'username': ['用户名不存在或未绑定邮箱']})
            return Response(result)

        user = queryset.get()
        auth = {'user': user.username, 'token': settings.RESET_TOKEN}
        context = {'scheme': request.META.get('wsgi.url_scheme'),
                   'host': request.META.get('HTTP_HOST'),
                   'param': TimestampSigner().sign_object(auth),
                   'password': settings.RESET_PASSWORD}
        html = render_to_string('pan/reset.html', context)
        send_mail(
            subject='Tiny Cloud',
            message=html,
            from_email=None,
            recipient_list=[user.email],
            fail_silently=True,
            html_message=html
        )
        result = AjaxData(msg='已发送验证邮件')
        return Response(result)


class FileUploadView(APIView):
    """上传文件"""

    def post(self, request):
        file = request.data.get('file')
        if not file:
            return Response()

        used = request.session['terms']['used'] + file.size
        if used > request.session['terms']['storage']:
            return Response(status=status.HTTP_400_BAD_REQUEST)

        parent = folder = request.user.files.get(file_uuid=request.data.get('parent', request.session['root']))
        file_path = Path(parent.file_path) / file.name
        if Path(file_path).exists():
            return Response(status=status.HTTP_400_BAD_REQUEST)

        folder_list = []

        # 更新父文件夹大小
        while folder:
            folder.file_size += file.size
            folder.update_by = request.user
            folder_list.append(folder)
            folder = folder.folder

        # 开启事务，保证数据完整性
        with transaction.atomic():
            file_type = FileType.objects.get_or_create(suffix=Path(file.name).suffix, defaults={'type_name': '未知'})[0]
            user_file = GenericFile.objects.create(file_name=file.name, file_type=file_type, file_size=file.size,
                                                   file_path=file_path, folder=parent, create_by=request.user)
            GenericFile.objects.bulk_update(folder_list, ('file_size', 'update_by'))
            with open(settings.PAN_ROOT / file_path, 'wb') as f:
                for chunk in file.chunks():
                    f.write(chunk)

        request.session['terms']['used'] = used
        return Response(FileSerializer(user_file).data)


class FolderUploadView(APIView):
    """上传文件夹"""

    def post(self, request):
        files = request.data.getlist('files')
        paths = request.data.getlist('paths')
        name = request.data.get('name')

        if not files or not paths or not name:
            return Response()

        path_nums = len(paths)
        if path_nums * 2 > settings.DATA_UPLOAD_MAX_NUMBER_FIELDS:
            return Response(status=status.HTTP_400_BAD_REQUEST)

        used = request.session['terms']['used'] + sum(s.size for s in files)
        if used > request.session['terms']['storage']:
            return Response(status=status.HTTP_400_BAD_REQUEST)

        parent = request.user.files.get(file_uuid=request.data.get('parent', request.session['root']))
        parent_path = Path(parent.file_path)
        if (parent_path / name).exists():
            return Response(status=status.HTTP_400_BAD_REQUEST)

        file_list = []
        folder_list = []
        folder_dict = defaultdict(int)

        # 开启事务，保证数据完整性
        with transaction.atomic():
            for i in range(path_nums):
                relative_path = Path(paths[i])
                parts = relative_path.parts[:-1]
                parents = list(reversed(relative_path.parents))[1:]
                temp_folder = parent
                # 逐级创建目录
                for j in range(len(parts)):
                    part_path = parent_path / parents[j]
                    part_folder = GenericFile.objects.get_or_create(file_path=part_path, is_del=False, defaults={
                        'file_name': parts[j],
                        'folder': temp_folder,
                        'create_by': request.user,
                    })[0]
                    temp_folder = part_folder
                # 创建文件对象
                file = files[i]
                file_path = parent_path / paths[i]
                file_type = FileType.objects.get_or_create(suffix=Path(file.name).suffix,
                                                           defaults={'type_name': '未知'})[0]
                file_list.append(GenericFile(file_name=file.name, file_type=file_type, file_size=file.size,
                                             file_path=file_path, folder=temp_folder, create_by=request.user))

            # 计算父文件夹大小
            for item in file_list:
                folder = item.folder
                while folder:
                    folder_dict[folder] += item.file_size

pan/templates/pan/index.html
<!DOCTYPE html>{% load static %}
<html lang="zh" class="h-100">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'pan/vendor/mdb/mdb.min.css' %}" rel="stylesheet">
    <link href="{% static 'pan/vendor/font-awesome/all.min.css' %}" rel="stylesheet">
    <link href="{% static 'pan/css/style.css' %}" rel="stylesheet">
    <title>首页</title>
    <style>
        body {
            background: url("{% static 'pan/img/mountain.jpg' %}") no-repeat center center fixed;
            background-size: cover;
        }
    </style>
</head>
<body class="h-100">
<div class="mask" style="background-color: rgba(0, 0, 0, 0.6)">
    <nav class="navbar navbar-dark fixed-top">
        <div class="container-fluid">
            <a class="navbar-brand">Tiny Cloud</a>
            <ul class="navbar-nav ms-auto" id="authLink">
                <li class="nav-item">
                    <a class="nav-link" href="javascript:void(0)"
                       data-mdb-toggle="offcanvas" data-mdb-target="#authCanvas">登录 / 注册</a>
                </li>
            </ul>
            <ul class="navbar-nav ms-auto flex-row align-items-center" id="navbar">
                <li class="nav-item me-3">
                    <a class="nav-link" href="{% url 'pan:home' %}#storage"><i class="fa-solid fa-cloud"></i></a>
                </li>
                <li class="nav-item me-3">
                    <a class="nav-link" href="{% url 'pan:home' %}#history"><i class="fa-solid fa-clock"></i></a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link" href="javascript:void(0)" data-mdb-toggle="dropdown">
                        <img class="rounded-circle" id="avatar" src="" height="25" width="25"
                             alt="avatar">
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a class="dropdown-item" href="{% url 'pan:home' %}#profile">个人信息</a>
                        </li>
                        <li>
                            <a class="dropdown-item" id="logout" href="javascript:void(0)">退出登录</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
    <div class="h-100 d-flex justify-content-center align-items-center">
        <div id="shareCard" class="card" style="width: 18rem; display: none">
            <div class="card-header">
                <button type="button" class="float-end btn-close"></button>
            </div>
            <div class="card-body">
                <h5 class="card-title file-name"></h5>
                <div class="smaller" id="expiry"></div>
                <p class="smaller" id="summary" style="height: 8rem"></p>
                <div class="d-flex align-items-center border rounded p-2 mb-2">
                    <svg class="icon" aria-hidden="true">
                        <use xlink:href="#icon-file_default" xmlns="http://www.w3.org/2000/svg"
                             xmlns:xlink="http://www.w3.org/1999/xlink">
                        </use>
                    </svg>
                    <div class="ms-2 text-truncate smaller">
                        <div class="file-name"></div>
                        <div class="text-muted" id="size"></div>
                    </div>
                </div>
                <button type="button" class="btn btn-warning btn-rounded">下载</button>
            </div>
        </div>
        <div id="keyArea">
            <h1 class="text-white text-center mb-5">立即探索</h1>
            <div class="form-outline form-white" style="width: 15rem">
                <input type="text" id="key" class="form-control form-control-lg form-icon-trailing" maxlength="6"
                       autocomplete="off"/>
                <label class="form-label" for="key">输入6位口令</label>
                <i class="text-white fa-solid fa-key trailing"></i>
            </div>
        </div>
    </div>
</div>
<div class="offcanvas offcanvas-end" tabindex="-1" id="authCanvas" data-mdb-scroll="true" data-mdb-backdrop="false">
    <div class="offcanvas-header">
        <button type="button" class="btn-close" data-mdb-dismiss="offcanvas"></button>
    </div>
    <div class="offcanvas-body">
        <ul class="nav nav-pills mb-5">
            <li class="nav-item">
                <a class="nav-link active" id="loginTab" data-mdb-toggle="pill" href="#signIn">登录</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-mdb-toggle="pill" href="#signUp">注册</a>
            </li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane fade show active" id="signIn">
                <form class="row g-4" data-url="login" novalidate>
                    <div class="col-12">
                        <div class="form-outline">
                            <input type="text" id="username" name="username" class="form-control"
                                   maxlength="150" required/>
                            <label class="form-label" for="username">用户名</label>
                            <div class="invalid-feedback">不为空且长度小于150</div>
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="form-outline">
                            <input type="password" id="password" name="password" class="form-control"
                                   minlength="6" maxlength="128" required/>
                            <label class="form-label" for="password">密码</label>
                            <div class="invalid-feedback">长度大于6小于128</div>
                        </div>
                    </div>
                    <div class="col-12 d-flex justify-content-between">
                        <div class="form-check">
                            <input class="form-check-input me-2" id="remember" name="remember"
                                   type="checkbox" checked/>
                            <label class="form-check-label" for="remember">记住我</label>
                        </div>
                        <a href="#resetModal" data-mdb-toggle="modal">忘记密码？</a>
                    </div>
                    <div class="col-12">
                        <button class="btn btn-primary btn-block">登录</button>
                    </div>
                </form>
            </div>
            <div class="tab-pane fade" id="signUp">
                <form class="row g-4" data-url="register" novalidate>
                    <div class="col-12">
                        <div class="form-outline">
                            <input type="text" id="_username" name="username"
                                   class="form-control" maxlength="150" required/>
                            <label class="form-label" for="_username">用户名</label>
                            <div class="invalid-feedback">不为空且长度小于150</div>
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="form-outline">
                            <input type="password" id="password1" name="password1"
                                   class="form-control" minlength="6" maxlength="128" required/>
                            <label class="form-label" for="password1">密码</label>
                            <div class="invalid-feedback">长度大于6小于128</div>
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="form-outline">
                            <input type="password" id="password2" name="password2"
                                   class="form-control" minlength="6" maxlength="128" required/>
                            <label class="form-label" for="password2">确认密码</label>
                            <div class="invalid-feedback">长度大于6小于128</div>
                        </div>
                    </div>
                    <div class="col-12">
                        <button class="btn btn-primary btn-block">注册</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="toast-container position-fixed bottom-0 end-0 p-3">
    <div id="toast" class="toast">
        <div class="toast-header">
            <i></i>
            <button type="button" class="ms-auto btn-close" data-mdb-dismiss="toast"></button>
        </div>
        <div class="toast-body"></div>
    </div>
</div>
<div class="modal fade" id="resetModal" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">重置密码</h5>
                <button type="button" class="btn-close" data-mdb-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <p>填写用户名，服务器会给该用户绑定的邮箱发送一个验证邮件</p>
                <p class="text-muted small">注：收不到邮件请检查网络和邮箱的pop3/smtp服务是否开启</p>
                <form class="row gy-3" data-url="reset" novalidate>
                    <div class="col-12">
                        <div class="form-outline">
                            <input class="form-control" id="resetName" name="username" maxlength="150" required>
                            <label class="form-label" for="resetName">用户名</label>
                            <div class="invalid-feedback">请输入正确用户名</div>
                        </div>
                    </div>
                    <div class="col-12 text-end">
                        <button type="reset" class="btn btn-secondary">取消</button>
                        <button class="btn btn-primary">确认</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script src="{% static 'pan/vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'pan/vendor/mdb/mdb.min.js' %}"></script>
<script src="{% static 'pan/vendor/iconfont/iconfont.js' %}"></script>
<script src="{% static 'pan/js/utils.js' %}"></script>
<script src="{% static 'pan/js/config.js' %}"></script>
<script src="{% static 'pan/js/index.js' %}"></script>
</body>
</html>

pan/templates/pan/reset.html
<div>
    <h3>重置Tiny Cloud账户密码</h3>
    <a class="btn" href="{{ scheme }}://{{ host }}{% url 'pan:reset-done' param %}" target="_blank">重置密码</a>
    <p>用户你好，收到你的重置密码请求，请确认是否是你本人操作</p>
    <p>在30分钟内点击上方链接将你的账户密码重置为{{ password }}，重置后请尽快更改密码。</p>
    <p>谢谢！<br>
        Tiny Cloud
    </p>
</div>

pan/templates/pan/reset_done.html
<!DOCTYPE html>
<html lang="zh" class="h-100">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.bootcdn.net/ajax/libs/mdb-ui-kit/6.0.0/mdb.min.css" rel="stylesheet">
    <title>重置信息</title>
</head>
<body class="h-100">
<div class="d-flex justify-content-center align-items-center h-100">
    <section class="text-center">
        <h3 class="mb-3">
            {% if access %}你的账户密码已重置，请及时修改{% else %}该链接已过期{% endif %}
        </h3>
        <a class="btn btn-dark" href="{% url 'pan:index' %}">回到主页</a>
    </section>
</div>
</body>
</html>

pan/templates/pan/share.html
<!DOCTYPE html>{% load static %}
<html lang="zh" class="h-100">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'pan/vendor/mdb/mdb.min.css' %}" rel="stylesheet">
    <link href="{% static 'pan/css/style.css' %}" rel="stylesheet">
    <title>分享</title>
</head>
<body class="h-100">
<div id="wrapper" class="d-flex justify-content-center align-items-center h-100">
    <div class="card" style="width: 18rem; display: none">
        <div class="card-body">
            <h5 class="card-title file-name"></h5>
            <div class="smaller" id="expiry"></div>
            <p class="smaller" id="summary" style="height: 8rem"></p>
            <div class="d-flex align-items-center border rounded p-2 mb-2">
                <svg class="icon" aria-hidden="true">
                    <use xlink:href="#icon-file_default" xmlns="http://www.w3.org/2000/svg"
                         xmlns:xlink="http://www.w3.org/1999/xlink">
                    </use>
                </svg>
                <div class="ms-2 text-truncate smaller">
                    <div class="file-name"></div>
                    <div class="text-muted" id="size"></div>
                </div>
            </div>
            <button type="button" class="btn btn-warning btn-rounded ">下载</button>
            <a href="{% url 'pan:index' %}" class="btn btn-light btn-rounded ">回到主页</a>
        </div>
    </div>
</div>
<div class="toast-container position-fixed bottom-0 end-0 p-3">
    <div id="toast" class="toast">
        <div class="toast-header">
            <i></i>
            <button type="button" class="ms-auto btn-close" data-mdb-dismiss="toast"></button>
        </div>
        <div class="toast-body"></div>
    </div>
</div>
<script src="{% static 'pan/vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'pan/vendor/mdb/mdb.min.js' %}"></script>
<script src="{% static 'pan/vendor/iconfont/iconfont.js' %}"></script>
<script src="{% static 'pan/js/utils.js' %}"></script>
<script src="{% static 'pan/js/config.js' %}"></script>
<script>
    window.addEventListener('DOMContentLoaded', function () {
        let key = domutil.getURLParam('key')
        let wrapper = document.getElementById('wrapper')
        let toast = new mdb.Toast(document.getElementById('toast'))

        $.get(_urls.shareSecret, {key: key}, (data, status, xhr) => {
            if (xhr.status === 200) {
                let card = wrapper.querySelector('.card')
                card.querySelectorAll('.file-name').forEach((el) => el.textContent = data.file.file_name)
                card.querySelector('#summary').textContent = data.summary
                card.querySelector('#expiry').textContent = custom.humanizeTime(data.expire_time)
                card.querySelector('#size').textContent = custom.fileSizeFormat(data.file.file_size)
                card.querySelector('button').addEventListener('click', () => {
                    location.href = _urls.fileBinary(data.file.file_uuid)
                    toast.setIcon(_fontawsome.info).setText('正在打包请稍等').show()
                })
                card.style.setProperty('display', 'block')
            } else {
                let html = `<p>文件已过期</p><a class="btn btn-light btn-lg shadow-1" href="/">返回主页</a>`
                wrapper.insertAdjacentHTML('beforeend', templates.elEmpty(html))
            }
        })
    })
</script>
</body>
</html>